'use client';

import { Sparkles } from 'lucide-react';
import { useMarketStory } from '@/hooks/useAssistant';

function formatTime(iso: string) {
  return new Date(iso).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function parseSections(story: string): { heading: string; body: string }[] {
  const parts = story.split(/^### /m).filter(Boolean);
  return parts.map((part) => {
    const [heading, ...rest] = part.split('\n');
    return { heading: heading.trim(), body: rest.join('\n').trim() };
  });
}

/**
 * AI-generated narrative, grounded in this item's real price/change data and
 * real tracked headlines. Silently hides itself if the backend
 * isn't reachable or its local model is unavailable — this is a bonus panel, not
 * a load-bearing one, so failure shouldn't be alarming.
 */
export function AIMarketStory({ type, symbol }: { type: 'commodity' | 'fx'; symbol: string }) {
  const { data, isLoading, isError } = useMarketStory(type, symbol);

  if (isError) return null;

  return (
    <div className="card p-4">
      <div className="mb-2 flex items-center gap-1.5">
        <Sparkles size={13} className="text-accent" />
        <p className="text-sm font-medium text-ink">AI Market Story</p>
      </div>

      {isLoading && (
        <div className="space-y-2">
          <div className="h-3 w-full animate-pulse rounded bg-canvas-overlay" />
          <div className="h-3 w-5/6 animate-pulse rounded bg-canvas-overlay" />
          <div className="h-3 w-2/3 animate-pulse rounded bg-canvas-overlay" />
        </div>
      )}

      {data && (
        <div className="flex flex-col gap-3">
          {parseSections(data.story).map((section) => (
            <div key={section.heading}>
              <p className="text-[11px] font-medium uppercase tracking-wide text-ink-faint">{section.heading}</p>
              <p className="mt-0.5 whitespace-pre-wrap text-xs text-ink-muted">{section.body}</p>
            </div>
          ))}
          <p className="text-[10px] text-ink-faint">
            AI-generated by ProcureChain, grounded in data as of {formatTime(data.dataAsOf)} — can be wrong, not
            advice.
          </p>
        </div>
      )}
    </div>
  );
}
