'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import { Sparkles, User } from 'lucide-react';
import { useAskAssistant } from '@/hooks/useAssistant';
import { useTrackEngagement } from '@/hooks/useEngagement';

interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  isError?: boolean;
  dataAsOf?: string | null;
}

const EXAMPLE_PROMPTS = [
  'How has WTI crude oil moved recently?',
  'What is the current USD/ZAR exchange rate?',
  'Which tracked commodities have risen the most this week?',
];

function formatTime(iso: string) {
  return new Date(iso).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

export function AssistantChat({ initialQuestion }: { initialQuestion?: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const { mutate, isPending } = useAskAssistant();
  const bottomRef = useRef<HTMLDivElement>(null);
  const askedInitial = useRef(false);
  const track = useTrackEngagement();
  const startedConversation = useRef(false);

  function send(question: string) {
    const trimmed = question.trim();
    if (!trimmed || isPending) return;

    if (!startedConversation.current) {
      startedConversation.current = true;
      track('ai_conversation_started');
    }

    setMessages((prev) => [...prev, { role: 'user', content: trimmed }]);
    setInput('');

    mutate(
      { question: trimmed },
      {
        onSuccess: (data) => {
          setMessages((prev) => [...prev, { role: 'assistant', content: data.answer, dataAsOf: data.dataAsOf }]);
        },
        onError: (error) => {
          const message =
            (error as Error).message?.includes('not configured')
              ? "The AI Assistant isn't available on this backend right now. Please ask an administrator to check the Ollama connection."
              : "Couldn't reach the AI Assistant backend right now. This needs the API server running — it isn't in this preview environment.";
          setMessages((prev) => [...prev, { role: 'assistant', content: message, isError: true }]);
        },
      },
    );
  }

  useEffect(() => {
    if (initialQuestion && !askedInitial.current) {
      askedInitial.current = true;
      send(initialQuestion);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialQuestion]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isPending]);

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    send(input);
  }

  return (
    <div className="mx-auto flex h-[70vh] max-w-2xl flex-col">
      <div className="flex-1 overflow-y-auto rounded-t-xl2 border border-b-0 border-border bg-canvas-raised p-4">
        {messages.length === 0 && (
          <div className="flex h-full flex-col items-center justify-center text-center">
            <Sparkles size={24} className="mb-3 text-accent" />
            <p className="text-sm text-ink-muted">
              Ask a procurement question — answers are grounded in the live market data on this
              site, generated by ProcureChain's self-hosted intelligence engine.
            </p>
            <div className="mt-4 flex flex-wrap justify-center gap-2">
              {EXAMPLE_PROMPTS.map((prompt) => (
                <button
                  key={prompt}
                  type="button"
                  onClick={() => send(prompt)}
                  className="rounded-full border border-border-subtle px-3 py-1 text-xs text-ink-muted transition-colors hover:border-accent hover:text-ink"
                >
                  {prompt}
                </button>
              ))}
            </div>
          </div>
        )}

        <div className="flex flex-col gap-4">
          {messages.map((message, i) => (
            <div key={i} className={`flex gap-2.5 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}>
              <div
                className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${
                  message.role === 'user' ? 'bg-canvas-overlay text-ink-muted' : 'bg-accent/10 text-accent'
                }`}
              >
                {message.role === 'user' ? <User size={14} /> : <Sparkles size={14} />}
              </div>
              <div
                className={`max-w-[80%] whitespace-pre-wrap rounded-xl2 px-3.5 py-2.5 text-sm ${
                  message.role === 'user'
                    ? 'bg-accent text-white'
                    : message.isError
                      ? 'border border-negative/30 bg-negative/10 text-negative'
                      : 'card text-ink'
                }`}
              >
                {message.content}
                {message.dataAsOf && (
                  <p className="mt-2 text-[10px] text-ink-faint">Grounded in data as of {formatTime(message.dataAsOf)}</p>
                )}
              </div>
            </div>
          ))}
          {isPending && (
            <div className="flex items-center gap-2 text-xs text-ink-faint">
              <Sparkles size={13} className="animate-pulse text-accent" />
              Thinking…
            </div>
          )}
        </div>
        <div ref={bottomRef} />
      </div>

      <form onSubmit={handleSubmit} className="flex items-center gap-2 rounded-b-xl2 border border-border bg-canvas p-3">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask about commodities, exchange rates, market trends..."
          className="w-full rounded-lg border border-border bg-canvas-raised px-3 py-2 text-sm text-ink placeholder:text-ink-faint focus:border-accent focus:outline-none"
        />
        <button
          type="submit"
          disabled={isPending || !input.trim()}
          className="shrink-0 rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-accent-hover disabled:opacity-50"
        >
          Send
        </button>
      </form>
      <p className="mt-2 text-center text-[11px] text-ink-faint">
        AI-generated — grounded in real tracked market data, but can be wrong. Not financial or
        procurement advice; verify before acting.
      </p>
    </div>
  );
}
